CREATE TABLE IF NOT EXISTS TELEGRAM_USERS (chatId INT8 PRIMARY KEY);

CREATE TABLE IF NOT EXISTS PROMOTIONS (id VARCHAR(255) PRIMARY KEY, title VARCHAR(255), description VARCHAR(255), startDate TIMESTAMP, endDate TIMESTAMP);

-- INSERT INTO TELEGRAM_USERS (chatId) VALUES (?);